pipeline:
  name: CI-11556-Remote-Testing
  identifier: CI11556RemoteTesting
  projectIdentifier: ShobhitTesting
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: org.SSBitbucket
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "hello how are you"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
